// coverage:ignore-file

// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';

import '../_core.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CipherActionAdapter());
    registerAdapter(CipherAlgorithmAdapter());
    registerAdapter(CipherAlgorithmTypeAdapter());
  }
}
